# Generated by Django 4.1.3 on 2022-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='string', max_length=30)),
                ('edad', models.IntegerField(default=1)),
                ('fecha_de_nacimiento', models.DateField(default=1969)),
            ],
        ),
    ]
